### ISSUE TITLE
Cannot install plugin: 400 Bad Request error 

### ISSUE THREAD

**Issue by jforaker** [strapi/strapi-heroku-app#3]
Tried to install Graphql plugin, got error in console:

```
Request URL: https://myapp.herokuapp.com/admin/plugins/install
Request Method: POST
Status Code: 400 Bad Request


Payload:
{"plugin":"graphql","port":""}
```
![image](https://user-images.githubusercontent.com/2042031/41196974-38787080-6c1c-11e8-80c4-468324803566.png)

**Comment by lauriejim** [comment]
We will disable plugin marketplace in production env.
You can't create APIs when your API is live, will be the same with plugin installation.

**Comment by datboirog94** [comment]
This issue isn't appearing on only production environment....
