### ISSUE TITLE
heroku media upload fails

### ISSUE THREAD

**Issue by xargr** [strapi/strapi-heroku-app#6]
When I upload one media file into the model doesn't allow me. This happens only for heroku production. Keep in your mind that I have added heroku plugin aws s3 and In normal situations rather should allow me

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/wiki/Create-files-on-Heroku

**Comment by xargr** [comment]
I put my solution here for more information for other users. In heroku you can use Bucketeer addons, after that install strapi plugin aws:
`npm install strapi-upload-aws-s3@3.0.0-alpha.14.2.1
`

works fine for me
