### ISSUE TITLE
Deploy to Heroku Button - Strapi won't start

### ISSUE THREAD

**Issue by gerdums** [strapi/strapi-heroku-app#7]
I clicked the "Deploy to Heroku" button on this article: [https://blog.strapi.io/deploying-a-strapi-api-on-heroku/](https://blog.strapi.io/deploying-a-strapi-api-on-heroku/)

I then choose a name clicked Deploy app and let it run.

After it had finished, I clicked "Open App" but I got this page:
![error](https://user-images.githubusercontent.com/7407866/46679766-a6a2b400-cbb5-11e8-82e7-d599e886723b.png)

When I checked the logs, this is the ouput:
![logs](https://user-images.githubusercontent.com/7407866/46679925-f5e8e480-cbb5-11e8-9f8f-1275e1e036af.png)

**Comment by vlad-ovsyannikov** [comment]
Same for me- any ideas? i get warning: You appear to have cloned an empty repository.

**Comment by vlad-ovsyannikov** [comment]
⚠️ After i tried to deploy Strapi manually to Heroku i figured out - > UPDATE: in latest version of Strapi you will have to set the config value: Authentication database the value has to be the database name.

**Comment by lauriejim** [comment]
Yap there is a difference between version and the way to deploy on Heroku.

https://github.com/strapi/strapi/wiki/Deploy-on-Heroku

We will make an update of the article soon as possible.

thank for the issue.

**Comment by nikosolihin** [comment]
@Donila You sir are awesome
