### ISSUE TITLE
Invalid template repository: The source could not be retrieved.

### ISSUE THREAD

**Issue by ccarnino** [strapi/strapi-heroku-app#8]
The `Deploy to Heroku` button doesn't work. When I press it and then write the instance name, then I get the following errors from Heroku.

```
Invalid template repository:
The source could not be retrieved.

Archive URL not found.
We couldn't find an archive URL for this repository.
```

**Comment by lauriejim** [comment]
Hello ! 

I just try and it works ...

![screen shot 2018-12-11 at 11 35 30](https://user-images.githubusercontent.com/5716596/49794884-e9f5dc00-fd38-11e8-9e84-faee1e2a044c.png)

**Comment by ccarnino** [comment]
Hello.
I can confirm that now it works again.
Cheers
