### ISSUE TITLE
Content Type not showing after deploy to Heroku

### ISSUE THREAD

**Issue by hamidnoei** [strapi/strapi-heroku-app#9]
I added a content type in my development and did `npm run setup` in root directory and then deployed it to Heroku but the content type doesn't show up and I can't add any content.
Content type that I added is `work`.

![image](https://user-images.githubusercontent.com/12403641/52922877-7c46cd00-32f2-11e9-91b7-29781f415cab.png)

Thanks!

**Comment by lauriejim** [comment]
Hello @hamidnoei !

I think this article will help you to understand why the content type builder is not display on Heroku (productions environment) https://github.com/strapi/strapi/wiki/Create-files-on-Heroku

**Comment by hamidnoei** [comment]
Hey Jim,

Thanks for reply, I'm adding my content type locally and then deploy to Heroku, I know that `content type builder` plugin is not supposed to be in production, the problem is the content type itself which is `work` here is not showing up in production after I deploy to Heroku although I do `npm run setup` and build the admin and then deploy it.

**Comment by hamidnoei** [comment]
To make it more clear these are my content type in DEV and PROD:

LOCAL:
![image](https://user-images.githubusercontent.com/12403641/53139146-b57f7700-3556-11e9-955f-0f0f8da95a71.png)

PROD:
![image](https://user-images.githubusercontent.com/12403641/53139210-f37c9b00-3556-11e9-9553-e10f4eec1c25.png)

**Comment by lauriejim** [comment]
I just try and it work well..

**Comment by lauriejim** [comment]
I follow the instruction off the readme and deploy it.
Then I check all default content types are deployed on Heroku.
Then I run `npm i` in the local strapi aplication. Start the server and create a new content type via the admin panel.
Then I commit and push new file.
And all works.
